// Code generated by wit-bindgen-go. DO NOT EDIT.

package invoker

// Exports represents the caller-defined exports from "example:invoker/invoker".
var Exports struct {
	// Call represents the caller-defined, exported function "call".
	//
	//	call: func() -> string
	Call func() (result string)

	// Func2 represents the caller-defined, exported function "func2".
	//
	//	func2: func() -> string
	Func2 func() (result string)
}
