// Code generated by wit-bindgen-go. DO NOT EDIT.

package invoker

// This file contains wasmimport and wasmexport declarations for "example:invoker".

//go:wasmexport example:invoker/invoker#call
//export example:invoker/invoker#call
func wasmexport_Call() (result *string) {
	result_ := Exports.Call()
	result = &result_
	return
}

//go:wasmexport example:invoker/invoker#func2
//export example:invoker/invoker#func2
func wasmexport_Func2() (result *string) {
	result_ := Exports.Func2()
	result = &result_
	return
}
